routes/web.php
<?php

use App\Http\Controllers\EmpleadosController;
use App\Http\Controllers\ProductosController;
use App\Models\Empleados;
use App\Models\Productos;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\DB;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


// los customizados deben ir antes de los resources

// Empleados

Route::get('/empleados/agregar',function(){
    return view('empleados.create');
})->name('empleados.agregar');

Route::get('/empleados/delete/{empleado}',function(Empleados $empleado){
    $empleado->delete();
    return redirect()->route('empleados.index')->with('empleados',Empleados::all());
})->name("empleados.delete");

Route::get('/empleados/editar/{empleado}',function(Empleados $empleado){
    return view("empleados.edit",["empleado"=>$empleado]);
})->name('empleados.editar');


// Productos
Route::get('/productos/agregar',function(){
    return view('productos.create');
})->name('productos.agregar');

Route::get('/productos/delete/{producto}',function(Productos $producto){
    $producto->delete();
    return redirect()->route('productos.index')->with('productos',Productos::all());
})->name("productos.delete");

Route::get('/productos/editar/{producto}',function(Productos $producto){
    return view("productos.edit",["producto"=>$producto]);
})->name('productos.editar');

Route::resource('empleados',EmpleadosController::class);
Route::resource('productos',ProductosController::class);

app/Models/Empleados.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Empleados extends Model
{
    use HasFactory;
}

app/Http/Controllers/EmpleadosController.php
<?php

namespace App\Http\Controllers;

use App\Models\Empleados;
use Illuminate\Http\Request;
use Intervention\Image\Facades\Image;

class EmpleadosController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $empleados = Empleados::all();
        return view('empleados.index',['empleados'=>$empleados]);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $datosEmpleado=request()->except('_token');

        if ($request->hasfile('foto')){
            $datosEmpleado['foto']=$request->file('foto')->store('uploads','public');
        }
        Empleados::insert($datosEmpleado);

        $empleados = Empleados::all();
        return redirect()->route('empleados.index')->with('empleados',$empleados);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Empleados  $empleados
     * @return \Illuminate\Http\Response
     */
    public function show(Empleados $empleados)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Empleados  $empleados
     * @return \Illuminate\Http\Response
     */
    public function edit(Empleados $empleados)
    {
        //

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Empleados  $empleados
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Empleados $empleados)
    {
        //
        $datosEmpleado=request()->except('_token');

        if ($request->hasfile('foto')){
            $datosEmpleado['foto']=$request->file('foto')->store('uploads','public');
        }
        $empleadoActual = Empleados::find($request->empleado);
        $empleadoActual->nombreE = $request->nombreE;
        $empleadoActual->foto = $datosEmpleado['foto'];
        $empleadoActual->save();
        // return view('empleados.index',['empleados'=>Empleados::all()]);
        return redirect()->route('empleados.index')->with('empleados',Empleados::all());
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Empleados  $empleados
     * @return \Illuminate\Http\Response
     */
    public function destroy(Empleados $empleados)
    {

        dd($empleados);

        // return redirect()->route('empleados.index');

    }



}

resources/views/empleados/create.blade.php
@extends('layouts.base')
@section('title',"Empleados")
@section('nav')
    @include('partials._navEmpleados')
@endsection
@section('content')
<div class="card p-5 pt-1 w-50 m-auto">


    <div class="row justify-content-center mb-3">
        <div class="col-md-8">
            <h1 class="text-center">Crear Empleados</h1>
        </div>
    </div>
    <form method="POST" action="{{ route('empleados.store') }}" enctype="multipart/form-data">
        {{-- @csrf --}}
        {{ csrf_field() }}
        <div class="form-group">
            <label for="formGroupExampleInput">Nombre</label>
            <input type="text" class="form-control" id="formGroupExampleInput" placeholder="nombre" name="nombreE" required>
        </div>
        <br>
        <div class="form-group">
            <label for="formGroupExampleInput">Foto</label>
            <br>
            <input type="file" name="foto" id="foto" value="">
        </div>
        <button type="submit" class="btn btn-primary btn-block mt-4 w-100">Crear</button>
    </form>
</div>
@endsection

resources/views/empleados/edit.blade.php
@extends('layouts.base')
@section('title',"Empleados")
@section('nav')
    @include('partials._navEmpleados')
@endsection
@section('content')
<div class="card p-5 pt-1 w-50 m-auto">


    <div class="row justify-content-center mb-3">
        <div class="col-md-8">
            <h1 class="text-center">Editar Empleado</h1>
        </div>
    </div>
    <form method="POST" action="{{ route('empleados.update',['empleado'=>$empleado]) }}"enctype="multipart/form-data">
        {{-- @csrf --}}
        @method('PUT')
        {{ csrf_field() }}
        <div class="form-group">
            <label for="formGroupExampleInput">Nombre</label>
            <input type="text" class="form-control" id="formGroupExampleInput" placeholder="nombre" name="nombreE" required value="{{ $empleado->nombreE }}">
        </div>
        <div class="form-group">
            <label for="formGroupExampleInput">Foto</label>
            <br>
            <input type="file" name="foto" id="foto" value="">
        </div>
        <button type="submit" class="btn btn-primary btn-block">Editar</button>
    </form>
</div>
@endsection

resources/views/empleados/index.blade.php
@extends('layouts.base')
@section('title',"Empleados")
@section('nav')
    @include('partials._navEmpleados')
@endsection
@section('content')
<table class="table w-50 m-auto">
    <thead class="table">
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Nombre</th>
        <th scope="col">Foto</th>
        <th scope="col">acciones</th>
      </tr>
    </thead>
    <tbody>
    @foreach($empleados as $empleado)
        <tr>
            <td> {{ $empleado->id }}</td>
            <td> {{ $empleado->nombreE }}</td>
            <td><img src="{{ asset('storage/'.$empleado->foto) }}" alt="" style="height: 80px"></td>

            <td>
                <a type="button" class="btn btn-danger ml-auto" type="submit" href="{{ route('empleados.delete',['empleado'=>$empleado]) }}"><i class="far fa-trash-alt"></i></a>
                <a type="button" class="btn btn-primary" style="" href="{{ route('empleados.editar',['empleado'=>$empleado]) }}"><i class="fa fa-edit"></i></a>
            </td>
        </tr>
    @endforeach

    </tbody>
  </table>
@endsection