routes/web.php
<?php

use App\Http\Controllers\EmpleadosController;
use App\Http\Controllers\ProductosController;
use App\Models\Empleados;
use App\Models\Productos;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\DB;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


// los customizados deben ir antes de los resources

// Empleados

Route::get('/empleados/agregar',function(){
    return view('empleados.create');
})->name('empleados.agregar');

Route::get('/empleados/delete/{empleado}',function(Empleados $empleado){
    $empleado->delete();
    return redirect()->route('empleados.index')->with('empleados',Empleados::all());
})->name("empleados.delete");

Route::get('/empleados/editar/{empleado}',function(Empleados $empleado){
    return view("empleados.edit",["empleado"=>$empleado]);
})->name('empleados.editar');


// Productos
Route::get('/productos/agregar',function(){
    return view('productos.create');
})->name('productos.agregar');

Route::get('/productos/delete/{producto}',function(Productos $producto){
    $producto->delete();
    return redirect()->route('productos.index')->with('productos',Productos::all());
})->name("productos.delete");

Route::get('/productos/editar/{producto}',function(Productos $producto){
    return view("productos.edit",["producto"=>$producto]);
})->name('productos.editar');

Route::resource('empleados',EmpleadosController::class);
Route::resource('productos',ProductosController::class);

app/Models/Productos.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Productos extends Model
{
    use HasFactory;
}

app/Http/Controllers/ProductosController.php
<?php

namespace App\Http\Controllers;

use App\Models\Productos;
use Illuminate\Http\Request;

class ProductosController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $productos = Productos::all();
        // $categorias =

        return view('productos.index',['productos'=>$productos]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $datosProductos=request()->except('_token');

        if ($request->hasfile('img_producto')){
            $datosProductos['img_producto']=$request->file('img_producto')->store('uploads','public');
        }
        $datosProductos['precio_producto'] = (double) $request->precio_producto;
        Productos::insert($datosProductos);

        return redirect()->route('productos.index')->with('productos',Productos::all());
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Productos  $productos
     * @return \Illuminate\Http\Response
     */
    public function show(Productos $productos)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Productos  $productos
     * @return \Illuminate\Http\Response
     */
    public function edit(Productos $productos)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Productos  $productos
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Productos $productos)
    {
        //
        $datosProductos=request()->except('_token');

        if ($request->hasfile('img_producto')){
            $datosProductos['img_producto']=$request->file('img_producto')->store('uploads','public');
        }
        $productoActual = Productos::find($request->producto);
        $productoActual->nomb_producto = $request->nomb_producto;
        $productoActual->marca_id = $request->marca_id;
        $productoActual->categoria_id = $request->categoria_id;
        $productoActual->precio_producto = (double)$request->precio_producto;
        $productoActual->desc_producto = $request->desc_producto;
        $productoActual->caract_producto = $request->caract_producto;
        $productoActual->img_producto = $datosProductos['img_producto'];
        $productoActual->save();
        return redirect()->route('productos.index')->with('productos',Productos::all());
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Productos  $productos
     * @return \Illuminate\Http\Response
     */
    public function destroy(Productos $productos)
    {
        //
    }
}

resources/views/productos/create.blade.php
@extends('layouts.base')
@section('title',"Productos")
@section('nav')
    @include('partials._navProductos')
@endsection
@section('content')
<div class="card p-5 pt-1 w-50 m-auto">


    <div class="row justify-content-center mb-3">
        <div class="col-md-8">
            <h1 class="text-center">Crear Productos</h1>
        </div>
    </div>
    <form method="POST" action="{{ route('productos.store') }}" enctype="multipart/form-data">
        {{-- @csrf --}}
        {{ csrf_field() }}
        <div class="form-group">
            <label for="formGroupExampleInput">Nombre</label>
            <input type="text" class="form-control" id="formGroupExampleInput" placeholder="nombre" name="nomb_producto" required>
        </div>
        <div class="form-group">
            <label for="formGroupExampleInput">Marca ID</label>
            <input type="text" class="form-control" id="formGroupExampleInput" placeholder="marca" name="marca_id" required>
        </div>
        <div class="form-group">
            <label for="formGroupExampleInput">Categoria ID</label>
            <input type="text" class="form-control" id="formGroupExampleInput" placeholder="marca" name="categoria_id" required>
        </div>
        <div class="form-group">
            <label for="formGroupExampleInput">Precio</label>
            <input type="text" class="form-control" id="formGroupExampleInput" placeholder="precio" name="precio_producto" required>
        </div>
        <div class="form-group">
            <label for="formGroupExampleInput">Descripcion</label>
            <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" placeholder="descripcion" name="desc_producto" required></textarea>
        </div>
        <div class="form-group">
            <label for="formGroupExampleInput">Caracteristica</label>
            <input type="text" class="form-control" id="formGroupExampleInput" placeholder="cantidad" name="caract_producto" required>
        </div>
        <div class="form-group">
            <label for="formGroupExampleInput">Foto</label>
            <br>
            <input type="file" name="img_producto" id="foto" value="">
        </div>
        <button type="submit" class="btn btn-primary btn-block mt-4 w-100">Crear</button>
    </form>
</div>
@endsection

resources/views/productos/edit.blade.php
@extends('layouts.base')
@section('title',"Productos")
@section('nav')
    @include('partials._navProductos')
@endsection
@section('content')
<div class="card p-5 pt-1 w-50 m-auto">


    <div class="row justify-content-center mb-3">
        <div class="col-md-8">
            <h1 class="text-center">Editar Producto</h1>
        </div>
    </div>
    <form method="POST" action="{{ route('productos.update',['producto'=>$producto]) }}"enctype="multipart/form-data">
        {{-- @csrf --}}
        @method('PUT')
        {{ csrf_field() }}
        <div class="form-group">
            <label for="formGroupExampleInput">Nombre</label>
            <input type="text" class="form-control" id="formGroupExampleInput" placeholder="nombre" name="nomb_producto" required value="{{ $producto->nomb_producto }}">
        </div>
        <div class="form-group">
            <label for="formGroupExampleInput">Marca</label>
            <input type="text" class="form-control" id="formGroupExampleInput" placeholder="marca" name="marca_id" required value="{{ $producto->marca_id }}">
        </div>
        <div class="form-group">
            <label for="formGroupExampleInput">Categoria</label>
            <input type="text" class="form-control" id="formGroupExampleInput" placeholder="marca" name="categoria_id" required value="{{ $producto->categoria_id }}">
        </div>
        <div class="form-group">
            <label for="formGroupExampleInput">Precio</label>
            <input type="text" class="form-control" id="formGroupExampleInput" placeholder="precio" name="precio_producto" required value="{{ $producto->precio_producto }}">
        </div>
        <div class="form-group">
            <label for="formGroupExampleInput">Descripcion</label>
            <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" placeholder="descripcion" name="desc_producto" required>{{ $producto->desc_producto }}</textarea>
        </div>
        <div class="form-group">
            <label for="formGroupExampleInput">cantidad</label>
            <input type="text" class="form-control" id="formGroupExampleInput" placeholder="cantidad" name="caract_producto" required value="{{ $producto->caract_producto }}">
        </div>
        <div class="form-group">
            <label for="formGroupExampleInput">Foto</label>
            <br>
            <input type="file" name="img_producto" id="foto" value="">
        </div>
        <button type="submit" class="btn btn-primary btn-block">Editar</button>
    </form>
</div>
@endsection

resources/views/productos/index.blade.php
@extends('layouts.base')
@section('title',"Productos")
@section('nav')
    @include('partials._navProductos')
@endsection
@section('content')
<table class="table w-75 m-auto">
    <thead class="table">
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Nombre</th>
        <th scope="col">marca id</th>
        <th scope="col">categoria id</th>
        <th scope="col">precio</th>
        <th scope="col">descripcion</th>
        <th scope="col">caracteristica</th>
        <th scope="col">foto</th>
        <th scope="col">acciones</th>
      </tr>
    </thead>
    <tbody>
    @foreach($productos as $producto)
        <tr>
            <td> {{ $producto->id }}</td>
            <td> {{ $producto->nomb_producto }}</td>
            <td> {{ $producto->marca_id }}</td>
            <td> {{ $producto->categoria_id }}</td>
            <td> {{ $producto->precio_producto }}</td>
            <td> {{ $producto->desc_producto }}</td>
            <td> {{ $producto->caract_producto }}</td>
            <td><img src="{{ asset('storage/'.$producto->img_producto) }}" alt="" style="height: 80px"></td>
            <td>
                <a type="button" class="btn btn-danger ml-auto" type="submit" href="{{ route('productos.delete',['producto'=>$producto]) }}"><i class="far fa-trash-alt"></i></a>
                <a type="button" class="btn bg-primary" style="color: white"  href="{{ route('productos.editar',['producto'=>$producto]) }}"><i class="fa fa-edit"></i></a>
            </td>
        </tr>
    @endforeach

    </tbody>
  </table>
@endsection